mysql:
  path: localhost
  port: 3307
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: navigator_local
  username: root
  password: localpassword
  max-idle-conns: 0
  max-open-conns: 0
  log-mode: ""
  log-zap: false
jwt:
  signing-key: Nav1gat0r
  expiretime: 86400 # 有效期 秒
  cookies-domain: ""
hashids:
  salt: Nav1gat0r
  minlength: 6
static-resource-cdn-host: ""
host: http://localhost:9000
