mysql:
  path: 10.10.0.5
  port: 33077
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: navigator_sit
  username: navigator_user
  password: "" # 从环境变量中读取
  max-idle-conns: 0
  max-open-conns: 0
  log-mode: ""
  log-zap: false
jwt:
  signing-key: "" # 从环境变量中读取
  expiretime: 86400 # 有效期 秒
  cookies-domain: navigator-demo.builtopia.io
hashids:
  salt: "" # 从环境变量中读取
  minlength: 6
static-resource-cdn-host: ""
host: https://navigator-demo.builtopia.io
